### PR TITLE
P3 components

### PR DESCRIPTION
**Pull request by yuriy-fix**
Fixes https://github.com/vaadin/components-team-tasks/issues/334

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/base-starter-angular/1)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[README.md, line 36 at r1](https://beta.reviewable.io/reviews/vaadin/base-starter-angular/1#-L9KGwOQ3XV8bds5D-WM:-L9KGwOQ3XV8bds5D-WN:bsfir29) ([raw file](https://github.com/vaadin/base-starter-angular/blob/919044c3ac904daf7ff0f0618bb4553d2abe9736/README.md#L36)):*
> ```Markdown
> ## Recreating this project
> 
> This project was generated with [Angular CLI](https://github.com/angular/angular-cli) version 1.6.5 with additional steps to include vaadin compoenents. You can recreate the project by following along these steps:
> ```

should capitalize Vaadin, also typo: compoEnents

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/base-starter-angular/1)*

**Comment by yuriy-fix** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 36 at r1](https://beta.reviewable.io/reviews/vaadin/base-starter-angular/1#-L9KGwOQ3XV8bds5D-WM:-L9KL4N_BTzGFMMgbVUb:b-896fix) ([raw file](https://github.com/vaadin/base-starter-angular/blob/919044c3ac904daf7ff0f0618bb4553d2abe9736/README.md#L36)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

should capitalize Vaadin, also typo: compoEnents
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/base-starter-angular/1)*

**Comment by tomivirkki** [comment]
*[package.json, line 26 at r2](https://beta.reviewable.io/reviews/vaadin/base-starter-angular/1#-L9KOWzZ6Gw5efuPgklt:-L9KOWzZ6Gw5efuPgklu:bjbzm5s) ([raw file](https://github.com/vaadin/base-starter-angular/blob/d9ae848e0d673b0b8dd09d4b356ec9297f437de7/package.json#L26)):*
> ```JSON
>     "@angular/router": "^5.2.0",
>     "@codebakery/origami": "^1.3.4",
>     "@vaadin/vaadin-button": "2.0.0-pre.1",
> ```

Should we depend on `^2.0.0-pre.1` so npm would pick up newer releases?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/base-starter-angular/1)*

**Comment by yuriy-fix** [comment]
Review status: 9 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[package.json, line 26 at r2](https://beta.reviewable.io/reviews/vaadin/base-starter-angular/1#-L9KOWzZ6Gw5efuPgklt:-L9KQ3x34rnJ7woNeODh:bdpcwdh) ([raw file](https://github.com/vaadin/base-starter-angular/blob/d9ae848e0d673b0b8dd09d4b356ec9297f437de7/package.json#L26)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Should we depend on `^2.0.0-pre.1` so npm would pick up newer releases?
</blockquote></details>

Sure, good point. Will align all starters to pick up newer releases.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/base-starter-angular/1)*

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/base-starter-angular/1#-:-L9KZJ_WEV3JevDuZy6Y:bnfp4nl)*

**Comment by tomivirkki** [comment]
*[a discussion](https://beta.reviewable.io/reviews/vaadin/base-starter-angular/1#-L9KabK-0XW6NT5K0d3o:-L9KabK00REjblRBorHc:b7wfbzv) (no related file):*
This only seems to work on Chrome.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/base-starter-angular/1)*

**Comment by platosha** [comment]
Reviewed 7 of 11 files at r1, 2 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[.angular-cli.json, line 11 at r3](https://beta.reviewable.io/reviews/vaadin/base-starter-angular/1#-L9KdCfa-0uMFaTZApuV:-L9KdCfa-0uMFaTZApuW:bxg5w2o) ([raw file](https://github.com/vaadin/base-starter-angular/blob/f14396c7773d620ef2edecdcdfd9a84dc387c890/.angular-cli.json#L11)):*
> ```JSON
>       "outDir": "dist",
>       "assets": [
>         "assets",
> ```

Let’s keep this folder. This is not something we created for bower, but part of the default `$ ng new PROJECT_NAME` output.

---

*[src/assets/.gitkeep, line 0 at r3](https://beta.reviewable.io/reviews/vaadin/base-starter-angular/1#-L9Kcx-mBUvdjKX6w5H1:-L9Kcx-n4FmeeanYq4W4:b-oyzzd) ([raw file](https://github.com/vaadin/base-starter-angular/blob/a51e4590f2afbb564fa1c767a5db9599f8931d0b/src/assets/.gitkeep#L0)):*
Why delete?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/base-starter-angular/1)*

**Comment by yuriy-fix** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[.angular-cli.json, line 11 at r3](https://beta.reviewable.io/reviews/vaadin/base-starter-angular/1#-L9KdCfa-0uMFaTZApuV:-L9KjP2FCaPraDo1Cp6C:b-bvwhm5) ([raw file](https://github.com/vaadin/base-starter-angular/blob/f14396c7773d620ef2edecdcdfd9a84dc387c890/.angular-cli.json#L11)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Let’s keep this folder. This is not something we created for bower, but part of the default `$ ng new PROJECT_NAME` output.
</blockquote></details>

Restored.

---

*[src/assets/.gitkeep, line  at r3](https://beta.reviewable.io/reviews/vaadin/base-starter-angular/1#-L9Kcx-mBUvdjKX6w5H1:-L9KjO3ZAelN867qUIKt:b-bvwhm5) ([raw file](https://github.com/vaadin/base-starter-angular/blob/a51e4590f2afbb564fa1c767a5db9599f8931d0b/src/assets/.gitkeep#L)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Why delete?
</blockquote></details>

Restored.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/base-starter-angular/1)*

**Comment by yuriy-fix** [comment]
Review status: 6 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/base-starter-angular/1#-L9KabK-0XW6NT5K0d3o:-L9KtNe-2gZo4glAjBS8:b-bw8e14) (no related file):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This only seems to work on Chrome.
</blockquote></details>

Updated.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/base-starter-angular/1)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 4 of 11 files at r1, 2 of 2 files at r3, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/base-starter-angular/1#-:-L9KwZk91l03zzmBxebL:bnfp4nl)*

**Comment by platosha** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/base-starter-angular/1#-:-L9Kwk4W4YUP_FsOopMa:bnfp4nl)*

**Pull request merged**
