### PR TITLE
Add angular.json, support @angular/cli@6.0.0

### LINKED ISSUE #8: Local workspace file ('angular.json') could not be found.
hoehmann@XXXXX MINGW64 /d/Dev/git/base-starter-angular (master)
$ ng serve
Local workspace file ('angular.json') could not be found.
Error: Local workspace file ('angular.json') could not be found.
    at WorkspaceLoader._getProjectWorkspaceFilePath (C:\Users\hoehmann\AppData\Roaming\npm\node_modules\@angular\cli\models\workspace-loader.js:37:19)
    at WorkspaceLoader.loadWorkspace (C:\Users\hoehmann\AppData\Roaming\npm\node_modules\@angular\cli\models\workspace-loader.js:24:21)
    at ServeCommand._loadWorkspaceAndArchitect (C:\Users\hoehmann\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:195:32)
    at ServeCommand.<anonymous> (C:\Users\hoehmann\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:47:25)
    at Generator.next (<anonymous>)
    at C:\Users\hoehmann\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\hoehmann\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:3:12)
    at ServeCommand.initialize (C:\Users\hoehmann\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:46:16)
    at Object.<anonymous> (C:\Users\hoehmann\AppData\Roaming\npm\node_modules\@angular\cli\models\command-runner.js:87:23)

### PR DESCRIPTION
**Pull request by limonte**
Fixes #8 

`angular.json` is automatically generated by `ng update @angular/cli` of newly released `@angular/cli@6.0.0`:

image

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/base-starter-angular/9)

### CODE REVIEW

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/base-starter-angular/9#-:-LC3yPUz1uspLb5C6eUM:bnfp4nl)*

**Comment by jedwantstocode** [comment]
sadly, this did not fix my issue. when I try running npm start after the installation, I still got the same errors.

**Comment by asifaftab87** [comment]
https://stackoverflow.com/questions/49810580/error-local-workspace-file-angular-json-could-not-be-found 
Here I found solution

**Comment by EmilianoGaytan** [comment]
same here, "sadly issue not fixed"

**Pull request merged**
